language: android
sudo: required
jdk: oraclejdk8
dist: precise
before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
  - tools
  - build-tools-28.0.3
  - build-tools-29.0.2
  - build-tools-29.0.3
  - android-22
  - android-28
  - android-29
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
script:
- echo "Travis branch is $TRAVIS_BRANCH"
- echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
- chmod 755 gradlew
- ls -la
- travis_wait ./gradlew clean --stacktrace
- travis_wait ./gradlew jacocoTestReport --stacktrace
- travis_wait ./gradlew jacocoFullReport --stacktrace
- travis_wait ./gradlew coveralls --stacktrace
- travis_wait ./gradlew javadoc
notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: opensrp-fp/build/docs/javadoc/
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_f761570c4ae9_key -iv $encrypted_f761570c4ae9_iv
  -in google-services.json.enc -out google-services.json -d
