---
form: fp_start_visit
fields:
  - "gender"
  - "method_gender_type"
  - "referral"
  - "current_method"
  - "step3_method_on_file"
  - "step3_on_another_method"
  - "step3_method_at_intake"
  - "step3_prior_methods_used"
  - "step3_current_method"
  - "step5_issues_concerns"
  - "step5_issues_concerns_other"
  - "step6_method_requested"
  - "step7_method_exit"
  - "step7_methods_exit_secondary"
